"""Add security to collections

Revision ID: 0d64fe435308
Revises: dbffc4d3a331
Create Date: 2026-02-17 18:24:37.758934

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '0d64fe435308'
down_revision: Union[str, Sequence[str], None] = 'dbffc4d3a331'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('collection_members',
    sa.Column('collection_id', sa.CHAR(length=36), nullable=False),
    sa.Column('user_id', sa.CHAR(length=36), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['collection_id'], ['collections.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('collection_id', 'user_id')
    )
    op.create_index(op.f('ix_collection_members_collection_id'), 'collection_members', ['collection_id'], unique=False)
    op.create_index(op.f('ix_collection_members_user_id'), 'collection_members', ['user_id'], unique=False)
    op.add_column('collections', sa.Column('access_type', sa.Enum('PRIVATE', 'PASSWORD', 'LINK', 'LINK_AND_PASSWORD', name='accesscollectiontype'), nullable=False))
    op.add_column('collections', sa.Column('password_hash', sa.String(length=255), nullable=True))
    op.add_column('collections', sa.Column('invite_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_collections_invite_token'), 'collections', ['invite_token'], unique=True)
    op.drop_column('media_items', 'ep_count')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('ep_count', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_index(op.f('ix_collections_invite_token'), table_name='collections')
    op.drop_column('collections', 'invite_token')
    op.drop_column('collections', 'password_hash')
    op.drop_column('collections', 'access_type')
    op.drop_index(op.f('ix_collection_members_user_id'), table_name='collection_members')
    op.drop_index(op.f('ix_collection_members_collection_id'), table_name='collection_members')
    op.drop_table('collection_members')
    # ### end Alembic commands ###
