"""Add passive cascade delete to associations models

Revision ID: 2689b0aed7f5
Revises: d59871d3c597
Create Date: 2026-02-20 20:42:20.428112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '2689b0aed7f5'
down_revision: Union[str, Sequence[str], None] = 'd59871d3c597'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('collection_members', 'id')
    op.drop_column('media_items_collections', 'id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items_collections', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('collection_members', sa.Column('id', mysql.INTEGER(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
