"""Alter models relations.

Revision ID: 311e16a20ad4
Revises: 831a14b9eeac
Create Date: 2026-02-06 11:16:19.053343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '311e16a20ad4'
down_revision: Union[str, Sequence[str], None] = '831a14b9eeac'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('media_items_collections', 'collection_id',
               existing_type=mysql.INTEGER(),
               type_=sa.CHAR(length=36),
               existing_nullable=False)
    op.drop_constraint(op.f('media_items_collections_ibfk_1'), 'media_items_collections', type_='foreignkey')
    op.create_foreign_key(None, 'media_items_collections', 'collections', ['collection_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'media_items_collections', type_='foreignkey')
    op.create_foreign_key(op.f('media_items_collections_ibfk_1'), 'media_items_collections', 'media_items', ['collection_id'], ['id'], ondelete='CASCADE')
    op.alter_column('media_items_collections', 'collection_id',
               existing_type=sa.CHAR(length=36),
               type_=mysql.INTEGER(),
               existing_nullable=False)
    # ### end Alembic commands ###
