"""Alter relations

Revision ID: 3fe60b0366db
Revises: 54ef53753c50
Create Date: 2026-03-06 21:11:26.843896

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3fe60b0366db'
down_revision: Union[str, Sequence[str], None] = '54ef53753c50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('votes_ibfk_3'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_ibfk_3'), 'votes', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###
