"""Alter relations and add some optional fields.

Revision ID: 4bfd18c0b49d
Revises: 7af694df8267
Create Date: 2026-02-06 20:03:52.973630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '4bfd18c0b49d'
down_revision: Union[str, Sequence[str], None] = '7af694df8267'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('collections', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=True)
    op.alter_column('media_items', 'poster',
               existing_type=mysql.VARCHAR(length=150),
               nullable=True)
    op.drop_constraint(op.f('votes_ibfk_1'), 'votes', type_='foreignkey')
    op.drop_constraint(op.f('votes_ibfk_2'), 'votes', type_='foreignkey')
    op.create_foreign_key(None, 'votes', 'media_items_collections', ['collection_id', 'item_id'], ['collection_id', 'media_item_id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'votes', type_='foreignkey')
    op.create_foreign_key(op.f('votes_ibfk_2'), 'votes', 'media_items', ['item_id'], ['id'])
    op.create_foreign_key(op.f('votes_ibfk_1'), 'votes', 'collections', ['collection_id'], ['id'])
    op.alter_column('media_items', 'poster',
               existing_type=mysql.VARCHAR(length=150),
               nullable=False)
    op.alter_column('collections', 'description',
               existing_type=mysql.VARCHAR(length=250),
               nullable=False)
    # ### end Alembic commands ###
