"""Remove useless row from MediaItem model

Revision ID: 54ef53753c50
Revises: fbcd084442cb
Create Date: 2026-03-06 19:27:29.646341

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '54ef53753c50'
down_revision: Union[str, Sequence[str], None] = 'fbcd084442cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('media_items', 'title_original')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('media_items', sa.Column('title_original', mysql.VARCHAR(length=250), nullable=True))
    # ### end Alembic commands ###
