"""Update CollectionMember model

Revision ID: 64a527f7b880
Revises: 3a733d2ba40e
Create Date: 2026-03-06 17:40:56.873062

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '64a527f7b880'
down_revision: Union[str, Sequence[str], None] = '3a733d2ba40e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_invite_token'), table_name='collections')
    op.create_index(op.f('ix_collections_invite_token'), 'collections', ['invite_token'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_collections_invite_token'), table_name='collections')
    op.create_index(op.f('ix_collections_invite_token'), 'collections', ['invite_token'], unique=True)
    # ### end Alembic commands ###
