"""Alter columns in associations models

Revision ID: d59871d3c597
Revises: f326818f92b3
Create Date: 2026-02-20 20:26:55.329608

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd59871d3c597'
down_revision: Union[str, Sequence[str], None] = 'f326818f92b3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('collection_members', sa.Column('id', sa.Integer(), nullable=False))
    op.add_column('media_items_collections', sa.Column('id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_votes_collection_id'), 'votes', ['collection_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_votes_collection_id'), table_name='votes')
    op.drop_column('media_items_collections', 'id')
    op.drop_column('collection_members', 'id')
    # ### end Alembic commands ###
