"""Alter relations between Collection and MediaItem.

Revision ID: dbffc4d3a331
Revises: 431f9ec1e6c1
Create Date: 2026-02-15 21:53:02.546120

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'dbffc4d3a331'
down_revision: Union[str, Sequence[str], None] = '431f9ec1e6c1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
